name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true # This is to set if any step fails then also other steps should run.
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include: 
          - node-version: 18   # node-version 18 and ubuntu combination job will be executed.
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12   # node-version 12 and window combination job will not be executed.
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci 
      - name: Build Project
        run: npm run build
  